package fhir

// ResourceScope describes whether a resource is patient-scoped, top-level, or auto-generated.
type ResourceScope int

const (
	PatientScoped  ResourceScope = iota // nested under a patient (e.g. Encounter, Observation)
	TopLevel                            // standalone resource (e.g. Practitioner, Organization)
	AutoGenerated                       // system-created, not directly edited (e.g. Provenance)
	SystemScoped                        // system-level alerts/supply (e.g. DetectedIssue)
)

// SearchParamDef describes a single FHIR search parameter and its SQLite mapping.
type SearchParamDef struct {
	Name      string // FHIR param name: "family", "code", "date"
	Type      string // "string", "token", "date", "reference"
	SQLColumn string // mapped SQLite column
	SQLTable  string // SQLite table name
	FHIRPath  string // documentation path expression
}

// ResourceDef describes a FHIR resource type supported by the system.
type ResourceDef struct {
	Type         string          // "Patient", "Immunization", etc.
	Scope        ResourceScope   // PatientScoped, TopLevel, AutoGenerated
	Interactions []string        // "read", "search-type", "create", "update", "delete"
	SearchParams []SearchParamDef
}

// registry holds all registered resource definitions keyed by resource type.
var registry = map[string]*ResourceDef{}

func init() {
	registerAll()
}

func registerAll() {
	// --- Existing patient-scoped resources ---
	register(&ResourceDef{
		Type:         ResourcePatient,
		Scope:        TopLevel,
		Interactions: []string{"read", "search-type", "create", "update", "delete"},
		SearchParams: []SearchParamDef{
			{Name: "family", Type: "string", SQLColumn: "family_name", SQLTable: "patients", FHIRPath: "Patient.name.family"},
			{Name: "given", Type: "string", SQLColumn: "given_names", SQLTable: "patients", FHIRPath: "Patient.name.given"},
			{Name: "gender", Type: "token", SQLColumn: "gender", SQLTable: "patients", FHIRPath: "Patient.gender"},
			{Name: "birthdate", Type: "date", SQLColumn: "birth_date", SQLTable: "patients", FHIRPath: "Patient.birthDate"},
			{Name: "active", Type: "token", SQLColumn: "active", SQLTable: "patients", FHIRPath: "Patient.active"},
		},
	})

	register(&ResourceDef{
		Type:         ResourceEncounter,
		Scope:        PatientScoped,
		Interactions: []string{"read", "search-type", "create", "update"},
		SearchParams: []SearchParamDef{
			{Name: "status", Type: "token", SQLColumn: "status", SQLTable: "encounters", FHIRPath: "Encounter.status"},
			{Name: "class", Type: "token", SQLColumn: "class_code", SQLTable: "encounters", FHIRPath: "Encounter.class"},
			{Name: "date", Type: "date", SQLColumn: "period_start", SQLTable: "encounters", FHIRPath: "Encounter.period"},
			{Name: "type", Type: "token", SQLColumn: "type_code", SQLTable: "encounters", FHIRPath: "Encounter.type"},
		},
	})

	register(&ResourceDef{
		Type:         ResourceObservation,
		Scope:        PatientScoped,
		Interactions: []string{"read", "search-type", "create"},
		SearchParams: []SearchParamDef{
			{Name: "code", Type: "token", SQLColumn: "code", SQLTable: "observations", FHIRPath: "Observation.code"},
			{Name: "category", Type: "token", SQLColumn: "category", SQLTable: "observations", FHIRPath: "Observation.category"},
			{Name: "date", Type: "date", SQLColumn: "effective_datetime", SQLTable: "observations", FHIRPath: "Observation.effectiveDateTime"},
			{Name: "status", Type: "token", SQLColumn: "status", SQLTable: "observations", FHIRPath: "Observation.status"},
		},
	})

	register(&ResourceDef{
		Type:         ResourceCondition,
		Scope:        PatientScoped,
		Interactions: []string{"read", "search-type", "create", "update"},
		SearchParams: []SearchParamDef{
			{Name: "clinical-status", Type: "token", SQLColumn: "clinical_status", SQLTable: "conditions", FHIRPath: "Condition.clinicalStatus"},
			{Name: "code", Type: "token", SQLColumn: "code", SQLTable: "conditions", FHIRPath: "Condition.code"},
		},
	})

	register(&ResourceDef{
		Type:         ResourceMedicationRequest,
		Scope:        PatientScoped,
		Interactions: []string{"read", "search-type", "create", "update"},
		SearchParams: []SearchParamDef{
			{Name: "status", Type: "token", SQLColumn: "status", SQLTable: "medication_requests", FHIRPath: "MedicationRequest.status"},
			{Name: "medication", Type: "token", SQLColumn: "medication_code", SQLTable: "medication_requests", FHIRPath: "MedicationRequest.medicationCodeableConcept"},
		},
	})

	register(&ResourceDef{
		Type:         ResourceAllergyIntolerance,
		Scope:        PatientScoped,
		Interactions: []string{"read", "search-type", "create", "update"},
		SearchParams: []SearchParamDef{
			{Name: "clinical-status", Type: "token", SQLColumn: "clinical_status", SQLTable: "allergy_intolerances", FHIRPath: "AllergyIntolerance.clinicalStatus"},
			{Name: "code", Type: "token", SQLColumn: "substance_code", SQLTable: "allergy_intolerances", FHIRPath: "AllergyIntolerance.code"},
			{Name: "criticality", Type: "token", SQLColumn: "criticality", SQLTable: "allergy_intolerances", FHIRPath: "AllergyIntolerance.criticality"},
		},
	})

	register(&ResourceDef{
		Type:         ResourceFlag,
		Scope:        PatientScoped,
		Interactions: []string{"read", "search-type", "create"},
		SearchParams: []SearchParamDef{
			{Name: "status", Type: "token", SQLColumn: "status", SQLTable: "flags", FHIRPath: "Flag.status"},
		},
	})

	// --- System-scoped resources ---
	register(&ResourceDef{
		Type:         ResourceDetectedIssue,
		Scope:        SystemScoped,
		Interactions: []string{"read", "search-type"},
		SearchParams: []SearchParamDef{
			{Name: "severity", Type: "token", SQLColumn: "severity", SQLTable: "detected_issues", FHIRPath: "DetectedIssue.severity"},
			{Name: "status", Type: "token", SQLColumn: "status", SQLTable: "detected_issues", FHIRPath: "DetectedIssue.status"},
		},
	})

	register(&ResourceDef{
		Type:         ResourceSupplyDelivery,
		Scope:        SystemScoped,
		Interactions: []string{"read", "search-type"},
	})

	// --- New patient-scoped resources (Phase 6.1) ---
	register(&ResourceDef{
		Type:         ResourceImmunization,
		Scope:        PatientScoped,
		Interactions: []string{"read", "search-type", "create"},
		SearchParams: []SearchParamDef{
			{Name: "status", Type: "token", SQLColumn: "status", SQLTable: "immunizations", FHIRPath: "Immunization.status"},
			{Name: "vaccine-code", Type: "token", SQLColumn: "vaccine_code", SQLTable: "immunizations", FHIRPath: "Immunization.vaccineCode"},
			{Name: "date", Type: "date", SQLColumn: "occurrence_datetime", SQLTable: "immunizations", FHIRPath: "Immunization.occurrenceDateTime"},
		},
	})

	register(&ResourceDef{
		Type:         ResourceProcedure,
		Scope:        PatientScoped,
		Interactions: []string{"read", "search-type", "create"},
		SearchParams: []SearchParamDef{
			{Name: "status", Type: "token", SQLColumn: "status", SQLTable: "procedures", FHIRPath: "Procedure.status"},
			{Name: "code", Type: "token", SQLColumn: "code", SQLTable: "procedures", FHIRPath: "Procedure.code"},
			{Name: "date", Type: "date", SQLColumn: "performed_datetime", SQLTable: "procedures", FHIRPath: "Procedure.performedDateTime"},
		},
	})

	// --- New top-level resources ---
	register(&ResourceDef{
		Type:         ResourcePractitioner,
		Scope:        TopLevel,
		Interactions: []string{"read", "search-type", "create", "update"},
		SearchParams: []SearchParamDef{
			{Name: "family", Type: "string", SQLColumn: "family_name", SQLTable: "practitioners", FHIRPath: "Practitioner.name.family"},
			{Name: "given", Type: "string", SQLColumn: "given_names", SQLTable: "practitioners", FHIRPath: "Practitioner.name.given"},
			{Name: "active", Type: "token", SQLColumn: "active", SQLTable: "practitioners", FHIRPath: "Practitioner.active"},
		},
	})

	register(&ResourceDef{
		Type:         ResourceOrganization,
		Scope:        TopLevel,
		Interactions: []string{"read", "search-type", "create"},
		SearchParams: []SearchParamDef{
			{Name: "name", Type: "string", SQLColumn: "name", SQLTable: "organizations", FHIRPath: "Organization.name"},
			{Name: "type", Type: "token", SQLColumn: "type", SQLTable: "organizations", FHIRPath: "Organization.type"},
			{Name: "active", Type: "token", SQLColumn: "active", SQLTable: "organizations", FHIRPath: "Organization.active"},
		},
	})

	register(&ResourceDef{
		Type:         ResourceLocation,
		Scope:        TopLevel,
		Interactions: []string{"read", "search-type", "create"},
		SearchParams: []SearchParamDef{
			{Name: "name", Type: "string", SQLColumn: "name", SQLTable: "locations", FHIRPath: "Location.name"},
			{Name: "type", Type: "token", SQLColumn: "type", SQLTable: "locations", FHIRPath: "Location.type"},
			{Name: "status", Type: "token", SQLColumn: "status", SQLTable: "locations", FHIRPath: "Location.status"},
		},
	})

	// --- System-scoped MeasureReport ---
	register(&ResourceDef{
		Type:         ResourceMeasureReport,
		Scope:        SystemScoped,
		Interactions: []string{"read", "search-type", "create"},
		SearchParams: []SearchParamDef{
			{Name: "status", Type: "token", SQLColumn: "status", SQLTable: "measure_reports", FHIRPath: "MeasureReport.status"},
			{Name: "type", Type: "token", SQLColumn: "type", SQLTable: "measure_reports", FHIRPath: "MeasureReport.type"},
			{Name: "date", Type: "date", SQLColumn: "period_start", SQLTable: "measure_reports", FHIRPath: "MeasureReport.period"},
		},
	})

	// --- Read-only StructureDefinition (profile discovery) ---
	register(&ResourceDef{
		Type:         ResourceStructureDefinition,
		Scope:        SystemScoped,
		Interactions: []string{"read", "search-type"},
	})

	// --- Auto-generated resources ---
	register(&ResourceDef{
		Type:         ResourceProvenance,
		Scope:        AutoGenerated,
		Interactions: []string{"read", "search-type"},
	})
}

func register(def *ResourceDef) {
	registry[def.Type] = def
}

// GetResourceDef returns the definition for a resource type, or nil if unknown.
func GetResourceDef(resourceType string) *ResourceDef {
	return registry[resourceType]
}

// AllResourceDefs returns definitions for all registered resource types.
func AllResourceDefs() []*ResourceDef {
	defs := make([]*ResourceDef, 0, len(registry))
	for _, def := range registry {
		defs = append(defs, def)
	}
	return defs
}

// IsKnownResource returns true if the resource type is registered.
func IsKnownResource(resourceType string) bool {
	_, ok := registry[resourceType]
	return ok
}

// ResourcesByScope returns all resource definitions matching the given scope.
func ResourcesByScope(scope ResourceScope) []*ResourceDef {
	var defs []*ResourceDef
	for _, def := range registry {
		if def.Scope == scope {
			defs = append(defs, def)
		}
	}
	return defs
}
