package fhir

import "testing"

func TestGetResourceDef_KnownTypes(t *testing.T) {
	known := []string{
		ResourcePatient, ResourceEncounter, ResourceObservation, ResourceCondition,
		ResourceMedicationRequest, ResourceAllergyIntolerance, ResourceFlag,
		ResourceDetectedIssue, ResourceSupplyDelivery,
		ResourceImmunization, ResourceProcedure,
		ResourcePractitioner, ResourceOrganization, ResourceLocation,
		ResourceProvenance,
	}
	for _, rt := range known {
		def := GetResourceDef(rt)
		if def == nil {
			t.Errorf("GetResourceDef(%q) = nil, want non-nil", rt)
			continue
		}
		if def.Type != rt {
			t.Errorf("GetResourceDef(%q).Type = %q", rt, def.Type)
		}
	}
}

func TestGetResourceDef_Unknown(t *testing.T) {
	if def := GetResourceDef("FakeResource"); def != nil {
		t.Errorf("expected nil for unknown type, got %+v", def)
	}
}

func TestIsKnownResource(t *testing.T) {
	if !IsKnownResource(ResourcePatient) {
		t.Error("Patient should be known")
	}
	if IsKnownResource("FakeResource") {
		t.Error("FakeResource should not be known")
	}
}

func TestAllResourceDefs_Count(t *testing.T) {
	defs := AllResourceDefs()
	if len(defs) != 15 {
		t.Errorf("AllResourceDefs() returned %d defs, want 15", len(defs))
	}
}

func TestResourcesByScope(t *testing.T) {
	patientScoped := ResourcesByScope(PatientScoped)
	if len(patientScoped) < 7 {
		t.Errorf("PatientScoped resources = %d, want at least 7", len(patientScoped))
	}

	topLevel := ResourcesByScope(TopLevel)
	if len(topLevel) < 3 {
		t.Errorf("TopLevel resources = %d, want at least 3", len(topLevel))
	}

	autoGen := ResourcesByScope(AutoGenerated)
	if len(autoGen) < 1 {
		t.Errorf("AutoGenerated resources = %d, want at least 1", len(autoGen))
	}
}

func TestSearchParams_Populated(t *testing.T) {
	def := GetResourceDef(ResourcePatient)
	if def == nil {
		t.Fatal("Patient def is nil")
	}
	if len(def.SearchParams) == 0 {
		t.Error("Patient should have search params")
	}
	// Verify first param has all fields populated
	sp := def.SearchParams[0]
	if sp.Name == "" || sp.Type == "" || sp.SQLColumn == "" || sp.SQLTable == "" || sp.FHIRPath == "" {
		t.Errorf("search param has empty fields: %+v", sp)
	}
}
