from __future__ import annotations

import json
import logging
from collections import deque
from dataclasses import dataclass, field

from sentinel.store.models import Alert

logger = logging.getLogger(__name__)

SEVERITY_MAP = {
    "critical": "high",
    "high": "high",
    "moderate": "moderate",
    "low": "low",
}


def alert_to_fhir(alert: Alert) -> dict:
    """Convert a sentinel Alert to a FHIR DetectedIssue resource."""
    resource: dict = {
        "resourceType": "DetectedIssue",
        "status": "preliminary",
        "severity": SEVERITY_MAP.get(alert.severity, "moderate"),
        "code": {
            "coding": [{
                "system": "https://open-nucleus.dev/sentinel/alert-category",
                "code": alert.category or alert.type,
                "display": alert.title,
            }]
        },
        "detail": alert.description,
        "identified": alert.created_at,
    }

    if alert.patient_id:
        resource["patient"] = {"reference": f"Patient/{alert.patient_id}"}

    # AI provenance tags
    tags = []
    if alert.ai_generated:
        tags.append({
            "system": "https://open-nucleus.dev/sentinel/ai-provenance",
            "code": "ai-generated",
            "display": (
                f"AI-generated by {alert.ai_model}, "
                f"confidence: {alert.ai_confidence:.2f}, "
                f"reflections: {alert.reflection_iterations}"
            ),
        })
    else:
        tags.append({
            "system": "https://open-nucleus.dev/sentinel/ai-provenance",
            "code": "rule-only",
            "display": "Rule-based detection (LLM unavailable)",
        })

    if alert.rule_validated:
        tags.append({
            "system": "https://open-nucleus.dev/sentinel/ai-provenance",
            "code": "rule-validated",
            "display": "LLM finding confirmed by deterministic rules",
        })

    resource["meta"] = {"tag": tags}

    # Extensions
    extensions = []
    if alert.ai_reasoning:
        extensions.append({
            "url": "https://open-nucleus.dev/sentinel/ai-reasoning",
            "valueString": alert.ai_reasoning,
        })

    if alert.evidence:
        extensions.append({
            "url": "https://open-nucleus.dev/sentinel/evidence",
            "valueString": json.dumps(alert.evidence),
        })

    if extensions:
        resource["extension"] = extensions

    return resource


@dataclass
class EmissionQueueEntry:
    alert_id: str
    fhir_resource: dict
    retries: int = 0
    max_retries: int = 3


class EmissionQueue:
    """Queue for alert emissions to Patient Service. Stub implementation."""

    def __init__(self, max_size: int = 100) -> None:
        self._queue: deque[EmissionQueueEntry] = deque(maxlen=max_size)

    def enqueue(self, alert: Alert) -> None:
        fhir = alert_to_fhir(alert)
        entry = EmissionQueueEntry(alert_id=alert.id, fhir_resource=fhir)
        self._queue.append(entry)
        logger.info(
            "Enqueued alert %s for emission (queue depth: %d)",
            alert.id, len(self._queue),
        )

    async def emit(self, entry: EmissionQueueEntry) -> bool:
        """Stub: logs but doesn't call Patient Service yet."""
        logger.info(
            "Would emit DetectedIssue for alert %s to Patient Service "
            "(stub — not connected)",
            entry.alert_id,
        )
        return False

    @property
    def pending(self) -> int:
        return len(self._queue)

    def entries(self) -> list[dict]:
        return [
            {"alert_id": e.alert_id, "retries": e.retries}
            for e in self._queue
        ]
